// routesMap.jsx
export const routesMap = {
    /* ===== Quick Start ===== */
    "Why Market.trad Markets?": "/quickstart/why-markets",
    "What assets can I trade?": "/quickstart/assets",
    "What platform can I trade on?": "/quickstart/platform-options",
    "What account type do you offer": "/quickstart/account-types",
    "How to verify my account?": "/quickstart/verify-account",
    "How to deposite funds?": "/quickstart/deposit-funds",
    "How to withdraw funds?": "/quickstart/withdraw-funds",
    "How can I start trading?": "/quickstart/start-trading",
    "Create Account": "/quickstart/create-account",
  
    /* ===== Markets ===== */
    "Markets Overview": "/markets",
    Forex: "/markets/forex",
    Equities: "/market/equities",
    Commodities: "/markets/commodities",
    Energies: "/markets/commodities/energies",
    Metals: "/markets/commodities/metals",
    Futures: "/markets/futures",
    Energy: "/markets/futures/energy",
    Indices: "/markets/futures/indices",
    Other: "/markets/futures/other",
    Crypto: "/markets/crypto",
    Indices: "/markets/indices",
    
  
    /* ===== Platform ===== */
    TradingView: "/platforms/tradingview",
    cTrade: "/platforms/ctrade",
    "MetaTrade 4 (MT4)": "/platforms/mt4",
    "MetaTarde 5 (MT5)": "/platforms/mt5",
    "Market.trad CopyTrade": "/platforms/copytrade",
    "Market.trad Invest": "/platforms/invest",
    "Trading Tools": "/platforms/tradingtools",
    "VPS Trading": "/platforms/tradingtools/vpstrading",
    "Fix API Trading": "/platforms/tradingtools/fixAPItrading",
    "Zulu Trade": "/platforms/tradingtools/zulutrade",
    "Myfxbook": "/platforms/tradingtools/myfxbook",
  
    /* ===== Education ===== */
    "Education Hub": "/education",
    Webinars: "/education/webinars",
    "Beginner Forex Tutorial": "/education/forex/beginner",
    "Intermediate Forex Tutorial": "/education/forex/intermediate",
    "Advanced Forex Tutorial": "/education/forex/advanced",
    "Beginner Shares Tutorials": "/education/shares/beginner",
    "Intermediate Shares Tutorials": "/education/shares/intermediate",
    "Advanced Shares Tutorials": "/education/shares/advanced",
    "Beginner Commodities Tutorial": "/education/commodities/beginner",
    "Intermediate Commodities Tutorial": "/education/commodities/intermediate",
    "Advanced Commodities Tutorial": "/education/commodities/advanced",
    "Economic Calendar": "/education/economic-calendar",
    "Research Hub": "/education/research/hub",
    "Daily Market Analysis Snapshot": "/education/research/daily-analysis",
    "Watch Upcoming Trading Opportunities": "/education/research/opportunities",
    "Daily Insight Podcast": "/education/research/podcast",
    "Trading Research": "/education/research/trading",
    "Investment Research": "/education/research/investment",
    "Demo Trade": "/education/demo-trade",
  
    /* ===== About ===== */
    "About Us": "/about",
    "Awarded by Industry": "/about/awards",
    "About Comparison": "/about/comparison",
    "Company News": "/about/news",
    Compliance: "/about/compliance",
    "Security of Funds": "/about/security-funds",
  
    /* ===== Support ===== */
    "Getting Started": "/support/getting-started",
    "Account Support": "/support/account-support",
    "Platform Support": "/support/platform-support",
    "Market Support": "/support/market-support",
    "Economic Calendar": "/support/economic-calendar",
    "Contact Support": "/support/contact-support",
    "How to create an account?": "/support/getting-started/create-account",
    "How to verify your account?": "/support/getting-started/verify-account",
    "How to fund your account?": "/support/getting-started/fund-account",
    "How to link your trading platform?": "/support/getting-started/link-platform",
    "How to place your first trade?": "/support/getting-started/first-trade",
    "Secure Client Area": "/support/platform/secure-client",
    "Platform TradingView": "/support/platform/tradingview",
    "Platform cTrade": "/support/platform/ctrade",
    "Platform MetaTrade 4": "/support/platform/mt4",
    "Platform MetaTrade 5": "/support/platform/mt5",
    "How to open a share investing account?": "/support/platform/invest/open-share-account",
    "How to fund your share investing account?": "/support/platform/invest/fund-share-account",
    "How to install and log into Market.trad Invest?": "/support/platform/invest/install-login",
    "How to convert currency in a Cash Account?": "/support/platform/invest/currency-conversion",
    "Trading Conditions": "/support/market/trading-conditions",
    "Trading Hour Changes": "/support/market/trading-hours",
    "Contract Specifications": "/support/market/contract-specs",
    "Contract Expiries": "/support/market/contract-expiries",
    
    "Education Hub Support": "/support/education-hub",
    "Support Economic Calendar": "/support/economic-calendar",
    "Contact Us": "/support/contact",
  };
  
  export default routesMap;